name: CI/CD
on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']
  schedule:
    - cron: '0 14 30 * *' # Monthly at 2pm on the 30th
jobs:
  test:
    name: 🐘 PostgreSQL ${{ matrix.pg }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pg: [14, 13, 12, 11, 10, 9.6, 9.5, 9.4, 9.3, 9.2, 9.1, 9.0, 8.4]
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t pgxn-tools-test .
      - run: "docker run --rm --mount \"type=bind,src=$(pwd)/test,dst=/repo\" pgxn-tools-test /repo/runtest.sh ${{ matrix.pg }}"
      - run: echo "${{ github.ref }}"
  publish:
    name: Push Docker image to Docker Hub
    # Publish main when the test job succeeds and it's not a pull request.
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request' && needs.test.result == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build and Push to Docker Hub
        # https://github.com/marketplace/actions/build-and-push-docker-images
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: pgxn/pgxn-tools
          tag_with_ref: true
          tags: latest,bullseye
